Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,7 +9,7 @@ jobs:
       - run: 
           name: Build step for C code
           command: |
-             gcc giggle.c -o giggle.out | echo "${PIPESTATUS[0]}" | tee ~/cmd_full_output 
+             gc giggle.c -o giggle.out | echo "${PIPESTATUS[0]}" | tee ~/cmd_full_output 
       - run: 
           name: Running out file and Store the ouput to html file
           command: |
@@ -33,6 +33,29 @@ jobs:
              git add index.html
              git commit -m " report for build output [skip ci]"
              git push
+      - run:
+          name: Sending failure message to GH Page
+          command: |
+             rm index.html
+             echo "<div class="text">" > index.html
+             echo "<pre>" >> index.html
+             echo -e "CI-BRANCH:$CIRCLE_BRANCH" >> index.html
+             echo -e "CI-BUILD_NUM:$CIRCLE_BUILD_NUM" >> index.html
+             echo -e "Build Failed" >> index.html
+             echo "</pre>" >> index.html
+             echo "</div>" >> index.html
+             git config --global user.email "kishorekumar015@gmail.com"
+             git config --global user.name "kkumarta"
+             git clone https://github.com/kkumarta/demo-giggle.git
+             git config --global user.email "kishorekumar015@gmail.com"
+             git config --global user.name "kkumarta"
+             rm demo-giggle/docs/index.html
+             cp index.html demo-giggle/docs/index.html
+             cd demo-giggle/docs
+             git add index.html
+             git commit -m " report for build output [skip ci]"
+             git push
+          when: on_fail
       - store_artifacts:
           path: ~/work/giggle.out
           destination: /home/artifact
