Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,7 +11,7 @@ jobs:
           command: |
              
              echo "export test_var="Build"" >> $BASH_ENV
-             echo "export cmd_full_output=$(gc giggle.c -o giggle.out | tee ~/cmd_full_output)" >> $BASH_ENV
+             echo "export cmd_full_output=$(set -o pipefail | gc giggle.c -o giggle.out | tee ~/cmd_full_output)" >> $BASH_ENV
       - run: 
           name: Running out file and Store the ouput to html file
           
